package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Success open free account with use the phone number")
    void generatedTest() {
        step("Open https://vivid.money/en-eu/prime/", () -> {
            step("// todo: just add selenium action");
        });

        step("Tap on the button \"Open free account\"", () -> {
            step("// todo: just add selenium action");
        });

        step("The invitation page should have a text \"Enter your phone number or e-mail and we'll send you a link to download the Vivid app\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Input phone number", () -> {
            step("// todo: just add selenium action");
        });

        step("Tap the \"Invite me!\" button", () -> {
            step("// todo: just add selenium action");
        });

        step("The Congrats displayed", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://vivid.money/en-eu/prime/'", () ->
            open("https://vivid.money/en-eu/prime/"));

        step("Page title should have text 'Vivid Prime plan with Premium Features | Vivid Europe'", () -> {
            String expectedTitle = "Vivid Prime plan with Premium Features | Vivid Europe";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://vivid.money/en-eu/prime/'", () ->
            open("https://vivid.money/en-eu/prime/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}